### ISSUE TITLE
New repo for the extension

### ISSUE THREAD

**Issue by ghost** [nikitaKunevich/vscode-snippet-creator#18]
Hello guys,

I tried to contact nikita (without success) to maintain the extension. Here is the new repo i've made for it, the extension is already on the marketplace.

https://github.com/VincentKos/vscode-snippet-creator

Have a nice day.

**Comment by abulka** [comment]
Might be good to increment the version number in the new repo to 0.6 so that it superceded the 0.5 here. 

Being 0.1 in the new repo suggests that the new repo is actually older, and this confuses people in the marketplace - as both versions of this extension are currently being listed in the marketplace.  People are going to go for the latest numbered version - that's what I did.

**Comment by dzsquared** [comment]
@VincentKos will you copy the MIT license over to the new repo?  I'm working on a project for Azure Data Studio that will include components from this extension and would like to properly attribute the work

**Comment by ghost** [comment]
> 
> 
> @VincentKos will you copy the MIT license over to the new repo? I'm working on a project for Azure Data Studio that will include components from this extension and would like to properly attribute the work

I'll do it today.

**Comment by abulka** [comment]
@vnzko Why has the new repository disappeared? https://github.com/VincentKos/vscode-snippet-creator 

And the published extension itself `snippet-creator
vincentkos.snippet-creator v1.1.0` seems to have been deleted from the [vscode marketplace](https://marketplace.visualstudio.com/search?term=snippet-creator&target=VSCode&category=All%20categories&sortBy=Relevance)? I can't seem to find it anymore.

The extension was working fine and I rely on it every day - not to mention I contributed code to the that project.

**Comment by abulka** [comment]
I've spoken with Vincent - it looks like both the repo and marketplace extension were accidentally deleted (long story) and Vincent is happy for me to take over this extension and re-publish it in the marketplace.

- New github repo is https://github.com/abulka/vscode-snippet-creator 
- Marketplace https://marketplace.visualstudio.com/items?itemName=wware.snippet-creator

Or just search for `wware` in the marketplace.

I've reverted to the plain Javascript version because that's what I'm familiar with - there didn't seem to be any functionality changes in the typescript version , so nothing is lost.  Besides, the code I salvaged from my 1.0.0 extension installation directory was confusing, with nested directories inside `out` and such - so I had to revert to something sane to move forward.

The latest version is now `1.1.0`

Unfortunately the download count in the marketplace resets to `0` so its not going to show up easily amongst the hundreds of 'snippet' related plugins available.

P.S. If interested, please also consider checking out a related vscode extension of mine: [Snippets Explorer](https://marketplace.visualstudio.com/items?itemName=wware.snippets-explorer ) which displays all available language snippets in a TreeView. Just search for `wware` in the marketplace.

**Comment by ghost** [comment]
Nice to see it back online (and in my plugins list).

The link to snippets-explorer is broken (miss the dash)

**Comment by abulka** [comment]
> The link to snippets-explorer is broken (miss the dash)

Oops - thanks for picking that up - previous comment now edited and URL fixed.  ~~P.S. It doesn't work on Windows 10 yet but that will be fixed tomorrow.~~
